// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

#ifndef BDEP_DEFAULT_OPTIONS_FILES_HXX
#define BDEP_DEFAULT_OPTIONS_FILES_HXX

// Begin prologue.
//
//
// End prologue.

#include <bdep/common-options.hxx>

// Print page usage information.
//
namespace bdep
{
  ::bdep::cli::usage_para
  print_bdep_default_options_files_usage (::std::ostream&,
                                          ::bdep::cli::usage_para = ::bdep::cli::usage_para::none);
}

// Begin epilogue.
//
//
// End epilogue.

#endif // BDEP_DEFAULT_OPTIONS_FILES_HXX
