// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

// Begin prologue.
//
//
// End prologue.

namespace bdep
{
  // cmd_fetch_options
  //

  inline const bool& cmd_fetch_options::
  full () const
  {
    return this->full_;
  }

  inline bool& cmd_fetch_options::
  full ()
  {
    return this->full_;
  }

  inline void cmd_fetch_options::
  full (const bool& x)
  {
    this->full_ = x;
  }
}

// Begin epilogue.
//
//
// End epilogue.
