// -*- C++ -*-
//
// This file was generated by CLI, a command line interface
// compiler for C++.
//

// Begin prologue.
//
//
// End prologue.

namespace bdep
{
  // cmd_test_options
  //

  inline const bool& cmd_test_options::
  immediate () const
  {
    return this->immediate_;
  }

  inline bool& cmd_test_options::
  immediate ()
  {
    return this->immediate_;
  }

  inline void cmd_test_options::
  immediate (const bool& x)
  {
    this->immediate_ = x;
  }

  inline const bool& cmd_test_options::
  recursive () const
  {
    return this->recursive_;
  }

  inline bool& cmd_test_options::
  recursive ()
  {
    return this->recursive_;
  }

  inline void cmd_test_options::
  recursive (const bool& x)
  {
    this->recursive_ = x;
  }
}

// Begin epilogue.
//
//
// End epilogue.
