# file      : tests/buildfile
# copyright : Copyright (c) 2014-2018 Code Synthesis Ltd
# license   : MIT; see accompanying LICENSE file

define common: file
common{*}: extension = test

commons = common git project

./: test{* -{$commons}} common{$commons} $bdep
